project:
  type: website

website:
  title: "Synthetic Cognition"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - articles.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto


